### ISSUE TITLE
Having problem with chinese characters

### ISSUE THREAD

**Issue by hyyz17200** [Chronial/snapraid-runner#30]
2020-04-17 09:00:57,969 [INFO  ] ============================================================
2020-04-17 09:00:57,970 [INFO  ] Run started
2020-04-17 09:00:57,970 [INFO  ] ============================================================
2020-04-17 09:00:57,971 [INFO  ] Running diff...
2020-04-17 09:00:58,015 [OUTPUT] Loading state from D:/snapraid.content...
2020-04-17 09:01:07,945 [OUTPUT] Comparing...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Soft\Python38-32\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Soft\Python38-32\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "F:\SnapRAID\snapraid-runner.py", line 34, in tee_thread
    for line in iter(infile.readline, ""):
UnicodeDecodeError: 'gbk' codec can't decode byte 0x92 in position 1096: illegal multibyte sequence

**Comment by hyyz17200** [comment]
I have found a solution and made pull request. I don't know if it's the best way but this worked in my case.

BTW, I am running Windows 10 Chinese and Python 3.8 32bit.

Please review this pull request and if ok close my issue.

Thank you.

**Comment by Chronial** [comment]
What you chose is in fact the best way, since snapraid always outputs utf8 on windows:
http://www.snapraid.it/manual
> ### 11 Encoding
>  SnapRAID in Unix ignores any encoding. It reads and stores the file names with the same encoding used by the file-system.
>
> In Windows all the names read from the file-system are converted and processed in the UTF-8 format.
