### ISSUE TITLE
Python3 Error

### ISSUE THREAD

**Issue by kyleinprogress** [Chronial/snapraid-runner#35]
Getting an error when I try and run. 

Command to run:
```
sudo python3 /opt/snapraid-runner/snapraid-runner.py -c /opt/snapraid-runner/snapraid-runner.conf
```
Error:
```
2020-08-04 14:41:42,612 [INFO  ] ============================================================
2020-08-04 14:41:42,612 [INFO  ] Run started
2020-08-04 14:41:42,613 [INFO  ] ============================================================
2020-08-04 14:41:42,613 [INFO  ] Running touch...
2020-08-04 14:41:42,613 [ERROR ] Run failed due to unexpected exception:
Traceback (most recent call last):
 File "/opt/snapraid-runner/snapraid-runner.py", line 233, in main
   run()
 File "/opt/snapraid-runner/snapraid-runner.py", line 256, in run
   snapraid_command("touch")
 File "/opt/snapraid-runner/snapraid-runner.py", line 58, in snapraid_command
   errors="replace"
TypeError: __init__() got an unexpected keyword argument 'encoding'
```

**Versions:**
_Ubuntu:_ 16.04
_Python:_ 3.5.2
_Snapraid:_ 11.5
_Snapraid Runner:_ Current

**Comment by kyleinprogress** [comment]
Figures...as soon as I post the issue I figure it out.

`New in version 3.6: encoding and errors were added.`

So you need at least 3.6 to run this.
