### ISSUE TITLE
Sending mail with Gmail SMTP server

### ISSUE THREAD

**Issue by li442il** [Chronial/snapraid-runner#4]
Hello,

I had this error message with " host = smtp.gmail.com"  :

2015-04-27 21:47:08,792 [ERROR ] Failed to send email
Traceback (most recent call last):
  File "C:\snapraid-movies1\runner\snapraid-runner.py", line 108, in finish
    send_email(is_success)
  File "C:\snapraid-movies1\runner\snapraid-runner.py", line 93, in send_email
    server = smtplib.SMTP_SSL('smtp.gmail.com', 587)
  File "C:\Program Files (x86)\Python\lib\smtplib.py", line 792, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "C:\Program Files (x86)\Python\lib\smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "C:\Program Files (x86)\Python\lib\smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "C:\Program Files (x86)\Python\lib\smtplib.py", line 798, in _get_socket
    new_socket = ssl.wrap_socket(new_socket, self.keyfile, self.certfile)
  File "C:\Program Files (x86)\Python\lib\ssl.py", line 891, in wrap_socket
    ciphers=ciphers)
  File "C:\Program Files (x86)\Python\lib\ssl.py", line 566, in __init__
    self.do_handshake()
  File "C:\Program Files (x86)\Python\lib\ssl.py", line 788, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:581)

adding "server.starttls()"  and some ehlo to : 

    if config["smtp"]["user"]:
        server.ehlo()
        server.starttls()
        server.ehlo()
        server.login(config["smtp"]["user"], config["smtp"]["password"])
    server.sendmail(
        config["email"]["from"],
        [config["email"]["to"]],
        msg.as_string())
    server.quit()

solved my issue :)

**Comment by Chronial** [comment]
Have you tried just using port `465` with SSL instead?

**Comment by Chronial** [comment]
see #6 on how to send mails via gmail.
