### ISSUE TITLE
Unicode Decode Error

### ISSUE THREAD

**Issue by ianduryfury** [Chronial/snapraid-runner#40]
I'm getting this error when I try to use snapraid runner. I'm guessing its probably down to me rather than the script. Maybe a problematic character in a file name?

I'm using windows 10 pro, latest version of python installed.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\Utilities\Python\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "D:\Utilities\Python\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Utilities\Snapraid Runner\snapraid-runner.py", line 34, in tee_thread
    for line in iter(infile.readline, ""):
  File "D:\Utilities\Python\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 890: character maps to <undefined>
```

**Comment by Chronial** [comment]
You are using a rather old version of snapraid-runner. This is an actual bug, that has been fixed for a while. But that is more my fault than yours – I forgot to mark a release since the bugfix. If you download the current version, your problem should be gone.
