### ISSUE TITLE
charmap codec script crash

### ISSUE THREAD

**Issue by MaleNurse** [Chronial/snapraid-runner#42]
```
2021-02-22 05:00:05,418 [OUTPUT] update "PoolPart.f864afd4-776e-4e9d-8df8-42c18f34f8eb/Music/AURORA/All My Demons Greeting Me as a Friend (2016)/02 - Conqueror.flac"
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\snapraid\Scripts\snapraid-runner.py", line 34, in tee_thread
    for line in iter(infile.readline, ""):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 3447: character maps to <undefined>
```

This is not confined to any particular file and occurs on every run attempt.

System info:
```
Edition	Windows 10 Pro
Version	20H2
Installed on	‎24-‎Oct-‎20
OS build	19042.804
Experience	Windows Feature Experience Pack 120.2212.551.0
Python 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)] on win32
```

**Comment by Chronial** [comment]
Which version of snapraid-runner are you running?

**Comment by MaleNurse** [comment]
So I'm not sure what version I was on, it was downloaded a couple months ago and when I checked modified date vs last commit date I thought mine was newer. But apparently not b/c when I compared the scripts there were differences and when I redownloaded it everything went fine. Not sure what changed between yesterday and today, but I'll just nod my head and go w/ it. Thanks!

**Comment by Chronial** [comment]
Looks like you were running the version that I tagged as the latest release. That is severely outdated by now, I will have to update that.
