### ISSUE TITLE
Failed To Send Email

### ISSUE THREAD

**Issue by elproducto** [Chronial/snapraid-runner#7]
Scripts is functioning properly, except for dispatching email.  I got the following error when i ran the script manually.

`2016-04-10 04:08:33,672 [ERROR ] Failed to send email
Traceback (most recent call last):
  File "/opt/snapraid-runner/snapraid-runner.py", line 107, in finish
    send_email(is_success)
  File "/opt/snapraid-runner/snapraid-runner.py", line 92, in send_email
    server = smtplib.SMTP_SSL(**smtp)
  File "/usr/lib/python2.7/smtplib.py", line 792, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 797, in _get_socket
    new_socket = socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -2] Name or service not known`

**Comment by Chronial** [comment]
The smtp host you set in your config is not correct / does not exist.

**Comment by elproducto** [comment]
Thanks mistakenly put smtp.google.com instead of smtp.gmail.com.
